### ISSUE TITLE
Make encrypted secret configurable with Habitat?

### ISSUE THREAD

**Issue by paulcsmith** [microgit-com/lucky_encrypted#1]
Hi there! This looks great! It's awesome to have this available for people to use 🎉

One thought I have is to allow easier customization of the encrypted secret by using `Habitat` https://luckyframework.org/guides/getting-started/configuration#configuring-your-own-code

So for example you could do this:

```crystal
module LuckyEncrypted
  Habitat.create do
    setting secret : String
  end
end
```

Then in the readme you could suggest this:

```crystal
# In config/lucky_encrypted.cr
require "./server" # To get the configuration from the server
LuckyEncrypted.configure do |settings|
  settings.secret = Lucky::Server.settings.secret_key_base
end
```

This way people can re-use the secret key base, but can also use something from ENV, YAML or wherever else. What do you think?

**Comment by confact** [comment]
This is fixed now so will close this :)

**Comment by paulcsmith** [comment]
Awesome!
